name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php artisan test

      - name: Deploy to Server
        run: |
          ssh user@yourserver "cd /var/www/html/myapp && git pull origin main && php artisan migrate"
